//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dem_predpriyatie.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int Equipment_id { get; set; }
        public int Employee_id { get; set; }
        public int Status_equipment_id { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Status_equipment Status_equipment { get; set; }
    }
}
