//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dem_predpriyatie.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Order_id { get; set; }
        public int Specification_id { get; set; }
        public int Client_id { get; set; }
        public int Status_id { get; set; }
        public int Department_id { get; set; }
        public System.DateTime Date_start { get; set; }
        public Nullable<System.DateTime> Date_end { get; set; }
        public decimal Summ_order { get; set; }
        public int Quantity_product { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual Specification Specification { get; set; }
        public virtual Status Status { get; set; }
    }
}
