//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dem_predpriyatie.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Specification()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Specification_id { get; set; }
        public int Warehouse_id { get; set; }
        public int Recipe_id { get; set; }
        public int Product_id { get; set; }
        public int Quantity { get; set; }
        public int Remains { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Products Products { get; set; }
        public virtual Recipe Recipe { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
